ALTER TABLE MUSICIAN DROP CONSTRAINT MSICIANMUSICIANSID
ALTER TABLE MUSICIAN00 DROP CONSTRAINT MSCIAN00MSICIANSID
ALTER TABLE MUSICIAN02 DROP CONSTRAINT MSCIAN02MSICIANSID
DROP TABLE BOOK
DROP TABLE BOOK00
DROP TABLE COMPACTDISCVERSION00
DROP TABLE COMPACTDISCVERSION01
DROP TABLE COMPACTDISCVERSION02
DROP TABLE ITEM
DROP TABLE MUSICIAN
DROP TABLE MUSICIAN00
DROP TABLE MUSICIAN02
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
